In [7]:
!pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.9/644.9 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 84.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.9/319.9 kB 21.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 115.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 112.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 106.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 6.4 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.31.1
    Uninstalling protobuf-6.31.1:
      Successfully uninstalled protobuf-6.31.1


In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv")

In [3]:
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
reviews = data['review']

In [6]:
voc_size = 10000

### One hot Encoding

In [7]:
onehot_rep = [one_hot(sentence, voc_size) for sentence in reviews]
print(onehot_rep)

Output hidden; open in https://colab.research.google.com to view.

### Word Embedding Representaion

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
## pre-padding
sent_length = 400
embedded_docs = pad_sequences(onehot_rep, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ...  751 4361 9385]
 [   0    0    0 ... 2539 3734  175]
 [   0    0    0 ... 9949 8829 3511]
 ...
 [   0    0    0 ... 4629 2276 5839]
 [   0    0    0 ... 5971 3057 6056]
 [   0    0    0 ...  184 2161 7178]]


In [10]:
embedded_docs[21212]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [11]:
dim = 50

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.build(input_shape=(None, sent_length))
model.compile(optimizer='adam', loss='mse')

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 400, 50)        │       500,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 500,000 (1.91 MB)

 Trainable params: 500,000 (1.91 MB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[[ 0.00944088, -0.02259678,  0.02061651, ...,  0.00055261,
          0.01504735, -0.03547732],
        [ 0.00944088, -0.02259678,  0.02061651, ...,  0.00055261,
          0.01504735, -0.03547732],
        [ 0.00944088, -0.02259678,  0.02061651, ...,  0.00055261,
          0.01504735, -0.03547732],
        ...,
        [ 0.01805839,  0.04101015,  0.00598412, ...,  0.01633152,
          0.0365845 ,  0.01332803],
        [-0.04303898, -0.03494834,  0.00197018, ..., -0.02077302,
         -0.03047801, -0.03162395],
        [-0.03002958, -0.04216439, -0.04580954, ..., -0.01689089,
          0.04086902, -0.01651598]]], dtype=float32)

In [15]:
print(model.predict(embedded_docs))

1563/1563 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step
[[[ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
   -0.03547732]
  [ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
   -0.03547732]
  [ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
   -0.03547732]
  ...
  [ 0.01805839  0.04101015  0.00598412 ...  0.01633152  0.0365845
    0.01332803]
  [-0.04303898 -0.03494834  0.00197018 ... -0.02077302 -0.03047801
   -0.03162395]
  [-0.03002958 -0.04216439 -0.04580954 ... -0.01689089  0.04086902
   -0.01651598]]

 [[ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
   -0.03547732]
  [ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
   -0.03547732]
  [ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
   -0.03547732]
  ...
  [-0.04407427 -0.04002916  0.03343693 ...  0.04951899  0.00428784
   -0.04138028]
  [ 0.04173228  0.01147489 -0.00136527 ...  0.01254047 -0.00420774
   -0.03272267]
  [-0.04875133  0.03503201 -0.0

In [16]:
print(model.predict(embedded_docs)[21])

1563/1563 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
[[ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
  -0.03547732]
 [ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
  -0.03547732]
 [ 0.00944088 -0.02259678  0.02061651 ...  0.00055261  0.01504735
  -0.03547732]
 ...
 [-0.03658626  0.04965541  0.0424622  ...  0.02968678  0.00506958
   0.04318334]
 [ 0.02807153 -0.04328656 -0.02191495 ... -0.02277678 -0.03144529
  -0.02405573]
 [ 0.03771168 -0.00938703  0.03305533 ...  0.00473119  0.00730108
   0.00490283]]
